// Fake Event Data - For Reference Only (NOT Seeded)
// Copy and use this data as needed

const fakeEventData = [
  {
    title: "Community Cleanup Drive",
    description: "Join us for a massive community cleanup drive to make our neighborhood cleaner and greener. We'll be focusing on local parks and streets. Everyone is welcome - bring friends and family!",
    date: new Date("2026-04-25T08:00:00Z"),
    startTime: "8:00 AM",
    endTime: "12:00 PM",
    location: "Central Park, Downtown",
    category: "Community",
    status: "upcoming",
    isPublished: true,
    maxParticipants: null,
    eventCapacity: 150,
    registrationDeadline: new Date("2026-04-23T23:59:59Z"),
    createdByRole: "ngo",
  },
  {
    title: "Health Awareness Workshop",
    description: "Learn about preventive health measures and wellness practices from certified health professionals. Topics include nutrition, fitness, and mental health. Free for all participants.",
    date: new Date("2026-04-28T10:00:00Z"),
    startTime: "10:00 AM",
    endTime: "1:00 PM",
    location: "Community Hall, West Side",
    category: "Health",
    status: "upcoming",
    isPublished: true,
    maxParticipants: null,
    eventCapacity: 200,
    registrationDeadline: new Date("2026-04-26T23:59:59Z"),
    createdByRole: "ngo",
  },
  {
    title: "Tree Plantation Initiative",
    description: "Be part of our mission to plant 500 trees this season. We'll provide saplings, tools, and training. Perfect opportunity to contribute to environmental conservation and meet like-minded people.",
    date: new Date("2026-05-05T07:00:00Z"),
    startTime: "7:00 AM",
    endTime: "11:00 AM",
    location: "Green Valley Agricultural Land",
    category: "Environment",
    status: "upcoming",
    isPublished: true,
    maxParticipants: null,
    eventCapacity: 100,
    registrationDeadline: new Date("2026-05-03T23:59:59Z"),
    createdByRole: "ngo",
  },
  {
    title: "Educational Scholarship Program Launch",
    description: "Attend the launch of our scholarship program for underprivileged students. Learn about eligibility, application process, and success stories from previous scholars. Scholarships worth 10 lakhs available.",
    date: new Date("2026-05-10T2:00:00Z"),
    startTime: "2:00 PM",
    endTime: "4:00 PM",
    location: "Education Center, North District",
    category: "Education",
    status: "upcoming",
    isPublished: true,
    maxParticipants: null,
    eventCapacity: 250,
    registrationDeadline: new Date("2026-05-08T23:59:59Z"),
    createdByRole: "ngo",
  },
  {
    title: "Sports Tournament for Youth",
    description: "Annual youth sports tournament featuring cricket, badminton, and volleyball. Open for teams from ages 15-25. Winners will get trophies and certificates. Registration fees are minimal to keep it accessible.",
    date: new Date("2026-05-15T09:00:00Z"),
    startTime: "9:00 AM",
    endTime: "5:00 PM",
    location: "Sports Complex, Stadium Road",
    category: "Sports",
    status: "upcoming",
    isPublished: true,
    maxParticipants: null,
    eventCapacity: 300,
    registrationDeadline: new Date("2026-05-12T23:59:59Z"),
    createdByRole: "admin",
  },
  {
    title: "Cultural Festival Celebration",
    description: "Celebrate our rich cultural heritage with traditional performances, food stalls, crafts, and music. Experience the diversity of our community through dance, theater, and art exhibits.",
    date: new Date("2026-05-20T4:00:00Z"),
    startTime: "4:00 PM",
    endTime: "10:00 PM",
    location: "Town Square, City Center",
    category: "Cultural",
    status: "upcoming",
    isPublished: true,
    maxParticipants: null,
    eventCapacity: 500,
    registrationDeadline: new Date("2026-05-18T23:59:59Z"),
    createdByRole: "ngo",
  },
  {
    title: "Free Medical Camp",
    description: "Free health checkup camp with qualified doctors and medical staff. Patients can avail free consultation, blood pressure check, and diabetes screening. Medicines will be provided at very subsidized rates.",
    date: new Date("2026-05-22T09:00:00Z"),
    startTime: "9:00 AM",
    endTime: "3:00 PM",
    location: "Community Hospital, Main Street",
    category: "Health",
    status: "upcoming",
    isPublished: true,
    maxParticipants: null,
    eventCapacity: 200,
    registrationDeadline: new Date("2026-05-21T23:59:59Z"),
    createdByRole: "ngo",
  },
  {
    title: "Skill Development Workshop - Digital Marketing",
    description: "Learn digital marketing basics, SEO, social media strategies, and content creation from industry experts. Get certificate of completion. Perfect for job seekers and entrepreneurs.",
    date: new Date("2026-05-25T10:00:00Z"),
    startTime: "10:00 AM",
    endTime: "1:00 PM",
    location: "Tech Hub, Business District",
    category: "Education",
    status: "upcoming",
    isPublished: true,
    maxParticipants: 50,
    eventCapacity: 50,
    registrationDeadline: new Date("2026-05-23T23:59:59Z"),
    createdByRole: "ngo",
  },
  {
    title: "Women Empowerment Seminar",
    description: "Interactive seminar on women entrepreneurship, financial literacy, and leadership. Hear inspiring stories from successful women entrepreneurs and get mentoring opportunities.",
    date: new Date("2026-06-01T11:00:00Z"),
    startTime: "11:00 AM",
    endTime: "2:00 PM",
    location: "Convention Center, Downtown",
    category: "Community",
    status: "upcoming",
    isPublished: true,
    maxParticipants: null,
    eventCapacity: 150,
    registrationDeadline: new Date("2026-05-30T23:59:59Z"),
    createdByRole: "ngo",
  },
  {
    title: "Beach Cleanup & Marine Conservation Drive",
    description: "Help protect our marine ecosystem by cleaning beaches and learning about ocean conservation. Activities include beach cleanup, sea turtle education, and plastic awareness program.",
    date: new Date("2026-06-05T06:00:00Z"),
    startTime: "6:00 AM",
    endTime: "10:00 AM",
    location: "Sandy Beach, Coastal Area",
    category: "Environment",
    status: "upcoming",
    isPublished: true,
    maxParticipants: null,
    eventCapacity: 100,
    registrationDeadline: new Date("2026-06-03T23:59:59Z"),
    createdByRole: "ngo",
  },
];

console.log("=".repeat(80));
console.log("FAKE EVENT DATA - DO NOT SEED TO DATABASE");
console.log("=".repeat(80));
console.log("\nTotal Events:", fakeEventData.length);
console.log("\nEvents:");
console.log(JSON.stringify(fakeEventData, null, 2));
console.log("\n" + "=".repeat(80));

export default fakeEventData;
