import mongoose from "mongoose";
import Ngo from "../models/ngo.model.js";
import "../config/loadEnv.js";
import connectDB from "../config/db.js";

const ngos = [
  {
    ngoName: "Asha Kiran Foundation",
    regType: "Public Trust",
    regNumber: "TRUST-MH-2010-001",
    estYear: 2010,
    darpanId: "MH/2010/0012345",
    panNumber: "AAATA1234A",
    description: "Asha Kiran Foundation works to provide quality education and nutrition support to orphaned children in Mumbai. We run 4 shelter homes and feed over 500 children daily.",
    state: "Maharashtra",
    district: "Mumbai Suburban",
    city: "Mumbai",
    pincode: "400051",
    address: "45, Andheri East, Mumbai, Maharashtra",
    contactName: "Priya Sharma",
    contactRole: "Founder & Director",
    phone: "9876543210",
    whatsapp: "9876543210",
    email: "info@ashakiran.org",
    website: "https://ashakiran.org",
    services: ["Education", "Child Welfare", "Nutrition"],
    ngoS3Id: "https://images.unsplash.com/photo-1488521787991-ed7bbaae773c?auto=format&fit=crop&w=800&q=80",
    agreeToTerms: true,
    isVerified: true,
    stats: { totalDonations: 145000, totalVolunteers: 48, totalGalleryItems: 12 }
  },
  {
    ngoName: "Vriddha Seva Trust",
    regType: "Society",
    regNumber: "SOC-DL-2008-042",
    estYear: 2008,
    darpanId: "DL/2008/0045678",
    panNumber: "AAATV5678B",
    description: "Vriddha Seva Trust is dedicated to the care and dignity of abandoned senior citizens in Delhi. We provide shelter, medical care, and emotional support to over 200 elders.",
    state: "Delhi",
    district: "New Delhi",
    city: "Delhi",
    pincode: "110001",
    address: "12, Connaught Place, New Delhi, Delhi",
    contactName: "Ramesh Gupta",
    contactRole: "Secretary",
    phone: "9811234567",
    whatsapp: "9811234567",
    email: "contact@vriddhaseva.org",
    website: "https://vriddhaseva.org",
    services: ["Elderly Care", "Medical Aid", "Shelter"],
    ngoS3Id: "https://images.unsplash.com/photo-1576765608622-067973a79f53?auto=format&fit=crop&w=800&q=80",
    agreeToTerms: true,
    isVerified: true,
    stats: { totalDonations: 98000, totalVolunteers: 32, totalGalleryItems: 8 }
  },
  {
    ngoName: "Green Earth Society",
    regType: "Society",
    regNumber: "SOC-KA-2015-089",
    estYear: 2015,
    darpanId: "KA/2015/0078901",
    panNumber: "AAATG9012C",
    description: "Green Earth Society works on environmental conservation, waste management, and tree plantation drives across Bangalore. We have planted over 50,000 trees since 2015.",
    state: "Karnataka",
    district: "Bangalore Urban",
    city: "Bangalore",
    pincode: "560001",
    address: "78, MG Road, Bangalore, Karnataka",
    contactName: "Ananya Krishnan",
    contactRole: "President",
    phone: "9845678901",
    whatsapp: "9845678901",
    email: "hello@greenearth.org",
    website: "https://greenearth.org",
    services: ["Environment", "Community Welfare", "Education"],
    ngoS3Id: "https://images.unsplash.com/photo-1518531933037-91b2f5f229cc?auto=format&fit=crop&w=800&q=80",
    agreeToTerms: true,
    isVerified: true,
    stats: { totalDonations: 67000, totalVolunteers: 95, totalGalleryItems: 20 }
  },
  {
    ngoName: "Nari Shakti Foundation",
    regType: "Section 8 Company",
    regNumber: "SEC8-RJ-2012-033",
    estYear: 2012,
    darpanId: "RJ/2012/0034512",
    panNumber: "AAATN3456D",
    description: "Nari Shakti Foundation empowers widowed and underprivileged women in Rajasthan through skill development, microfinance, and legal aid. Over 3,000 women have been rehabilitated.",
    state: "Rajasthan",
    district: "Jaipur",
    city: "Jaipur",
    pincode: "302001",
    address: "34, Johari Bazaar, Jaipur, Rajasthan",
    contactName: "Sunita Meena",
    contactRole: "Managing Trustee",
    phone: "9414123456",
    whatsapp: "9414123456",
    email: "support@narishakti.org",
    website: "https://narishakti.org",
    services: ["Women Empowerment", "Skill Development", "Legal Aid"],
    ngoS3Id: "https://images.unsplash.com/photo-1529390079861-591de354faf5?auto=format&fit=crop&w=800&q=80",
    agreeToTerms: true,
    isVerified: true,
    stats: { totalDonations: 112000, totalVolunteers: 60, totalGalleryItems: 15 }
  },
  {
    ngoName: "Arogya Seva Samiti",
    regType: "Society",
    regNumber: "SOC-TN-2009-017",
    estYear: 2009,
    darpanId: "TN/2009/0056789",
    panNumber: "AAATA6789E",
    description: "Arogya Seva Samiti organises free medical camps and provides affordable healthcare to rural communities in Tamil Nadu. We conduct 50+ health camps every year.",
    state: "Tamil Nadu",
    district: "Chennai",
    city: "Chennai",
    pincode: "600001",
    address: "22, Anna Salai, Chennai, Tamil Nadu",
    contactName: "Dr. Vikram Rajan",
    contactRole: "Chief Medical Officer",
    phone: "9444567890",
    whatsapp: "9444567890",
    email: "arogya@arogyaseva.org",
    website: "https://arogyaseva.org",
    services: ["Medical Aid", "Community Welfare", "Health Camps"],
    ngoS3Id: "https://images.unsplash.com/photo-1584515933487-779824d29309?auto=format&fit=crop&w=800&q=80",
    agreeToTerms: true,
    isVerified: true,
    stats: { totalDonations: 134000, totalVolunteers: 75, totalGalleryItems: 18 }
  },
  {
    ngoName: "Pashuprem Animal Welfare",
    regType: "Public Trust",
    regNumber: "TRUST-GJ-2014-056",
    estYear: 2014,
    darpanId: "GJ/2014/0023456",
    panNumber: "AAATP2345F",
    description: "Pashuprem Animal Welfare rescues, treats, and rehabilitates stray and injured animals across Ahmedabad. Our shelter houses over 400 animals and our vet team treats 1,000+ animals monthly.",
    state: "Gujarat",
    district: "Ahmedabad",
    city: "Ahmedabad",
    pincode: "380001",
    address: "89, CG Road, Ahmedabad, Gujarat",
    contactName: "Kiran Patel",
    contactRole: "Founder",
    phone: "9925678901",
    whatsapp: "9925678901",
    email: "care@pashuprem.org",
    website: "https://pashuprem.org",
    services: ["Animal Welfare", "Veterinary Aid", "Rescue Operations"],
    ngoS3Id: "https://images.unsplash.com/photo-1587300003388-59208cc962cb?auto=format&fit=crop&w=800&q=80",
    agreeToTerms: true,
    isVerified: true,
    stats: { totalDonations: 56000, totalVolunteers: 40, totalGalleryItems: 25 }
  },
  {
    ngoName: "Shiksha Daan Society",
    regType: "Society",
    regNumber: "SOC-UP-2011-028",
    estYear: 2011,
    darpanId: "UP/2011/0067890",
    panNumber: "AAATS7890G",
    description: "Shiksha Daan Society runs free coaching centres and provides school kits to underprivileged children in Lucknow. Over 5,000 children have benefited since inception.",
    state: "Uttar Pradesh",
    district: "Lucknow",
    city: "Lucknow",
    pincode: "226001",
    address: "15, Hazratganj, Lucknow, Uttar Pradesh",
    contactName: "Aarav Singh",
    contactRole: "Director",
    phone: "9839012345",
    whatsapp: "9839012345",
    email: "contact@shikshadaan.org",
    website: "https://shikshadaan.org",
    services: ["Education", "Child Welfare", "Skill Development"],
    ngoS3Id: "https://images.unsplash.com/photo-1503676260728-1c00da094a0b?auto=format&fit=crop&w=800&q=80",
    agreeToTerms: true,
    isVerified: true,
    stats: { totalDonations: 89000, totalVolunteers: 55, totalGalleryItems: 10 }
  },
  {
    ngoName: "Kolkata Flood Relief Network",
    regType: "Section 8 Company",
    regNumber: "SEC8-WB-2007-011",
    estYear: 2007,
    darpanId: "WB/2007/0089012",
    panNumber: "AAATK8901H",
    description: "Kolkata Flood Relief Network provides emergency food, shelter, and rehabilitation support during floods and natural disasters across West Bengal. We have served 20,000+ disaster victims.",
    state: "West Bengal",
    district: "Kolkata",
    city: "Kolkata",
    pincode: "700001",
    address: "56, Park Street, Kolkata, West Bengal",
    contactName: "Debashish Banerjee",
    contactRole: "Chairman",
    phone: "9831234567",
    whatsapp: "9831234567",
    email: "relief@kolkataflood.org",
    website: "https://kolkataflood.org",
    services: ["Disaster Relief", "Shelter", "Nutrition"],
    ngoS3Id: "https://images.unsplash.com/photo-1469571486292-0ba58a3f068b?auto=format&fit=crop&w=800&q=80",
    agreeToTerms: true,
    isVerified: true,
    stats: { totalDonations: 178000, totalVolunteers: 120, totalGalleryItems: 30 }
  },
  {
    ngoName: "Hyderabad Rural Roads Trust",
    regType: "Public Trust",
    regNumber: "TRUST-TS-2016-073",
    estYear: 2016,
    darpanId: "TS/2016/0012678",
    panNumber: "AAATH1267I",
    description: "Hyderabad Rural Roads Trust builds and repairs roads, builds toilets, and installs clean water pipelines in remote villages of Telangana. 60+ villages have been transformed.",
    state: "Andhra Pradesh",
    district: "Hyderabad",
    city: "Hyderabad",
    pincode: "500001",
    address: "33, Banjara Hills, Hyderabad, Telangana",
    contactName: "Srinivas Reddy",
    contactRole: "Trustee",
    phone: "9848901234",
    whatsapp: "9848901234",
    email: "info@hydruraltrust.org",
    website: "https://hydruraltrust.org",
    services: ["Infrastructure", "Community Welfare", "Sanitation"],
    ngoS3Id: "https://images.unsplash.com/photo-1590650516494-0c8e4a4dd67e?auto=format&fit=crop&w=800&q=80",
    agreeToTerms: true,
    isVerified: true,
    stats: { totalDonations: 203000, totalVolunteers: 85, totalGalleryItems: 22 }
  },
  {
    ngoName: "Punjabiyan Di Shaan Foundation",
    regType: "Society",
    regNumber: "SOC-PB-2013-049",
    estYear: 2013,
    darpanId: "PB/2013/0034901",
    panNumber: "AAATP3490J",
    description: "Punjabiyan Di Shaan Foundation supports farmers in distress, provides free legal aid, and organises health camps in rural Punjab. Over 10,000 farming families have been helped.",
    state: "Punjab",
    district: "Ludhiana",
    city: "Ludhiana",
    pincode: "141001",
    address: "10, GT Road, Ludhiana, Punjab",
    contactName: "Gurpreet Kaur",
    contactRole: "General Secretary",
    phone: "9815678012",
    whatsapp: "9815678012",
    email: "hello@pdshaan.org",
    website: "https://pdshaan.org",
    services: ["Farmer Welfare", "Legal Aid", "Medical Aid"],
    ngoS3Id: "https://images.unsplash.com/photo-1500937386664-56d1dfef3854?auto=format&fit=crop&w=800&q=80",
    agreeToTerms: true,
    isVerified: true,
    stats: { totalDonations: 91000, totalVolunteers: 65, totalGalleryItems: 14 }
  },
  {
    ngoName: "Kerala Flood & Fisher Aid Society",
    regType: "Society",
    regNumber: "SOC-KL-2006-005",
    estYear: 2006,
    darpanId: "KL/2006/0056234",
    panNumber: "AAATK5623K",
    description: "Kerala Flood & Fisher Aid Society supports coastal fishing communities with financial aid, disaster relief, and livelihood training. Since the 2018 floods, we have rebuilt 800+ homes.",
    state: "Kerala",
    district: "Kochi",
    city: "Kochi",
    pincode: "682001",
    address: "7, Marine Drive, Kochi, Kerala",
    contactName: "Thomas Mathew",
    contactRole: "President",
    phone: "9847012345",
    whatsapp: "9847012345",
    email: "info@keralafish.org",
    website: "https://keralafish.org",
    services: ["Disaster Relief", "Livelihood Support", "Shelter"],
    ngoS3Id: "https://images.unsplash.com/photo-1593113598332-cd288d649433?auto=format&fit=crop&w=800&q=80",
    agreeToTerms: true,
    isVerified: true,
    stats: { totalDonations: 167000, totalVolunteers: 90, totalGalleryItems: 28 }
  },
  {
    ngoName: "Assam Tribal Education Mission",
    regType: "Section 8 Company",
    regNumber: "SEC8-AS-2018-061",
    estYear: 2018,
    darpanId: "AS/2018/0078345",
    panNumber: "AAATA7834L",
    description: "Assam Tribal Education Mission provides digital literacy, English education, and vocational training to tribal youth in remote areas of Assam. 2,500+ students enrolled so far.",
    state: "Assam",
    district: "Guwahati",
    city: "Guwahati",
    pincode: "781001",
    address: "22, GS Road, Guwahati, Assam",
    contactName: "Dipankar Borah",
    contactRole: "CEO",
    phone: "9435012678",
    whatsapp: "9435012678",
    email: "mission@assamtribal.org",
    website: "https://assamtribal.org",
    services: ["Education", "Tribal Welfare", "Digital Literacy"],
    ngoS3Id: "https://images.unsplash.com/photo-1427504494785-3a9ca7044f45?auto=format&fit=crop&w=800&q=80",
    agreeToTerms: true,
    isVerified: true,
    stats: { totalDonations: 43000, totalVolunteers: 38, totalGalleryItems: 9 }
  },
];

const seedNgos = async () => {
  try {
    await connectDB();
    console.log("✅ Connected to database");

    let inserted = 0;
    let skipped  = 0;

    for (const ngo of ngos) {
      const exists = await Ngo.findOne({ regNumber: ngo.regNumber });
      if (exists) {
        console.log(`⏭️  Skipped (already exists): ${ngo.ngoName}`);
        skipped++;
        continue;
      }
      await Ngo.create(ngo);
      console.log(`✅ Inserted: ${ngo.ngoName} — ${ngo.city}, ${ngo.state}`);
      inserted++;
    }

    console.log(`\n🎉 Done! Inserted: ${inserted} | Skipped: ${skipped}`);
    process.exit(0);
  } catch (err) {
    console.error("❌ Seed error:", err.message);
    process.exit(1);
  }
};

seedNgos();
